---
title: "Showcase"
description: |
  A showcase of distill websites and blogs. Add yours [here](https://github.com/jhelvy/distillery)!
output:
  distill::distill_article:
    toc: true
base_url: https://distillery.rbind.io
preview: images/distillery.png
params:
  update_all: FALSE
  check_url: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    message = FALSE,
    warning = FALSE
)

# Load libraries and functions
source(file.path("R", "functions.R"))
```

```{r build-content, include=FALSE}
sites <- clean_sites(read_csv("sites.csv"), params$check_url)
update_screenshots(sites, params$update_all)
rmd_chunks <- make_showcase_chunks(sites, image_width = 600)
button_filters <- buttons_filter(sites)
```

Use the buttons to filter the list of websites:

```{r insert-showcase, child = c(button_filters, rmd_chunks)}
```

```{css}

.filterDiv {
  display: none; /* Hidden by default */
}

/* The "show" class is added to the filtered elements */
.show {
  display: block;
}

/* Style the buttons */
.btn {
  border: none;
  outline: none;
  padding: 12px 16px;
  color: white;
  background-color: var(--bkgd-color, #0F2E3D);
  cursor: pointer;
}

/* Add a light grey background on mouse-over */
.btn:hover {
  background-color: #143d52;
  color: white
}

/* Add a dark background to the active button */
.btn.active {
  background-color: #1e5c7b;
  color: white;
}

.icon-link {
  font-size: 0.7rem;
  background-color: var(--color-primary);
  color: var(--color-white);
  padding: 3px 5px 3px 5px;
  margin: 0 2px 0 2px;
  border-radius: 5px; /* Rounded edges */
}

.icon-link:hover {
  background-color: var(--color-secondary);
  color: var(--color-white);
}
```

<script src = "js/filter-buttons.js"></script>